# Site settings
title: dwayne codling . me
email: dwayneandrecodling@gmail.com
description: Lecturer || Web Designer
exclude: ["node_modules",
  "gulpfile.js",
  "package.json",
  "preview.jpg",
  "README.md"]


# Build settings

markdown: kramdown
permalink: pretty


